package goof.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Todo")
public class Todo {
    private String id;
    private String todoText;
 
    public Todo() {
    }
    
    public Todo(String todoText) {
		super();
		this.todoText = todoText;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
 
    @DynamoDBAttribute
    public String getTodoText() {
        return todoText;
    }
    

	public void setId(String id) {
		this.id = id;
	}

	public void setTodoText(String todoText) {
		this.todoText = todoText;
	}
}
